title: Zhehao Zhang
position: Undergraduate Student
email: zzh12138@sjtu.edu.cn
keywords: minimal academic
github_link: https://github.com/zzh-SJTU
avatar: ./assets/img/IMG_5918.JPG
google_analytics: UA-111540567-4
favicon: ./assets/img/logo.jpg
favicon_dark: ./assets/img/logo.jpg
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
